Pet_Shop-Backend/Pet_Shop/Models/Bio.cs
namespace Pet_Shop.Models
{
    public class Bio
    {
        public int Id { get; set; }
        public string Location { get; set; }
        public string Phone { get; set; }
        public string Mail { get; set; }
        public string Twitter { get; set; }
        public string Facebook { get; set; }
        public string Linkedin { get; set; }
        public string Insta { get; set; }
    }
}

Pet_Shop-Backend/Pet_Shop/Areas/AdminF/Controllers/BioController.cs
using Microsoft.AspNetCore.Mvc;
using Pet_Shop.DAL;
using Pet_Shop.Models;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Pet_Shop.Areas.AdminF.Controllers
{
    [Area("AdminF")]
    public class BioController : Controller
    {
        private readonly AppDbContext _context;

        public BioController(AppDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            List<Bio> bios = _context.Bios.ToList();

            return View(bios);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            Bio Bio = await _context.Bios.FindAsync(id);
            if (Bio == null)
            {
                return NotFound();
            }
            _context.Bios.Remove(Bio); 
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Bio Bio)
        {
             
            Bio db = new Bio(); 
            db.Facebook = Bio.Facebook;
            db.Phone = Bio.Phone;
            db.Insta = Bio.Insta;
            db.Location = Bio.Location;
            db.Location = Bio.Location;
            db.Twitter = Bio.Twitter;
            db.Linkedin = Bio.Linkedin;
            await _context.Bios.AddAsync(db);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        public async Task<IActionResult> Update(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            Bio Bio = await _context.Bios.FindAsync(id);
            if (Bio == null) return NotFound();
            return View(Bio);
        }
        [HttpPost]
        public async Task<IActionResult> Update(Bio Bio, int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            
            Bio existtitle = _context.Bios.FirstOrDefault(c => c.Phone.ToLower() == Bio.Phone.ToLower());
            Bio db = await _context.Bios.FindAsync(id);
            if (existtitle != null)
            {
                if (db != existtitle)
                {
                    ModelState.AddModelError("Phone", "Phone Already Exist");
                    return View();
                }
            }
            if (db == null)
            {
                return NotFound();
            } 
            db.Facebook = Bio.Facebook;
            db.Phone = Bio.Phone;
            db.Insta = Bio.Insta;
            db.Location = Bio.Location;
            db.Location = Bio.Location;
            db.Twitter = Bio.Twitter;
            db.Linkedin = Bio.Linkedin;
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));

        }
        public async Task<IActionResult> Detail(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            Bio Bio = await _context.Bios.FindAsync(id);
            if (Bio == null)
            {
                return NotFound();
            }
            return View(Bio);
        }
    }
}

Pet_Shop-Backend/Pet_Shop/Areas/AdminF/Views/Bio/Create.cshtml
@model Bio
@{
    ViewData["Title"] = "Create";
    Layout = "~/Areas/AdminF/Views/Shared/_AdminLayout.cshtml";
}
<div class="container">
    <div class="row">
        <div class="col=md-12">
            <form class="forms-sample" method="post" enctype="multipart/form-data">

                <div class="form-group">
                    <label asp-for="Location">Location</label>
                    <input asp-for="Location" class="form-control" placeholder="Location">
                    <span asp-validation-for="Location"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Mail">Mail</label>
                    <input asp-for="Mail" class="form-control" placeholder="Mail">
                    <span asp-validation-for="Mail"></span>

                </div>
                <div class="form-group">
                    <label asp-for="Insta">Insta</label>
                    <input asp-for="Insta" class="form-control" placeholder="Insta">
                    <span asp-validation-for="Insta"></span>

                </div>
                <div class="form-group">
                    <label asp-for="Linkedin">Linkedin</label>
                    <input asp-for="Linkedin" class="form-control" placeholder="Linkedin">
                    <span asp-validation-for="Linkedin"></span>

                </div>
                <div class="form-group">
                    <label asp-for="Twitter">Twitter</label>
                    <input asp-for="Twitter" class="form-control" placeholder="Twitter">
                    <span asp-validation-for="Twitter"></span>

                </div>
                <div class="form-group">
                    <label asp-for="Facebook">Facebook</label>
                    <input asp-for="Facebook" class="form-control" placeholder="Facebook">
                    <span asp-validation-for="Facebook"></span>

                </div>
                <div class="form-group">
                    <label asp-for="Phone">Phone</label>
                    <input asp-for="Phone" class="form-control" placeholder="Phone">
                    <span asp-validation-for="Phone"></span>

                </div>
                <button type="submit" class="btn btn-primary mr-2">Create</button>
                <a asp-controller="bio" asp-action="Index" class="btn btn-primary">Back</a>
            </form>
        </div>

    </div>
</div>

Pet_Shop-Backend/Pet_Shop/Areas/AdminF/Views/Bio/Detail.cshtml
@model Bio
@{
    ViewData["Title"] = "Index";
    Layout = "~/Areas/Adminf/Views/Shared/_AdminLayout.cshtml";
}


<div class="row">
    <div class="col-lg-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">Bio Table</h4>
                <p class="card-description">
                    <a asp-controller="Bio" asp-action="Create" class="btn btn-primary">Create</a>
                    <div class="table-responsive">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>Location</th>
                                    <th>Phone</th>
                                    <th>Mail</th>
                                    <th>Insta</th>
                                    <th>Fb</th>
                                    <th>Twitter</th>
                                    <th>Linkedin</th>
                                    <th>Setting</th>
                                </tr>
                            </thead>
                            <tbody>


                                <tr>
                                    <td>@Model.Location</td>
                                    <td>@Model.Phone</td>
                                    <td>@Model.Mail</td>
                                    <td>@Model.Insta</td>
                                    <td>@Model.Facebook</td>
                                    <td>@Model.Twitter</td>
                                    <td>@Model.Linkedin</td>
                                    <td>
                                        <a class="btn btn-danger" asp-controller="Bio" asp-action="Delete" asp-route-id="@Model.Id">Delete</a>
                                        <a class="btn btn-dark" asp-controller="Bio" asp-action="Update" asp-route-id="@Model.Id">Update</a>
                                        <a class="btn btn-success" asp-controller="Bio" asp-action="Detail" asp-route-id="@Model.Id">Detail</a>

                                    </td>
                                </tr>


                            </tbody>
                        </table>

                    </div>
            </div>
        </div>
    </div>
</div>

Pet_Shop-Backend/Pet_Shop/Areas/AdminF/Views/Bio/Index.cshtml
@model IEnumerable<Bio>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Areas/Adminf/Views/Shared/_AdminLayout.cshtml";
}
@if (Model.Count() > 0)
{


    <div class="row">
        <div class="col-lg-12 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">Bio Table</h4>
                    <p class="card-description">
                        <a asp-controller="Bio" asp-action="Create" class="btn btn-primary">Create</a>
                        <div class="table-responsive">
                            <table class="table">
                                <thead>
                                    <tr>
                                        <th>Location</th>
                                        <th>Phone</th>
                                        <th>Mail</th>
                                        <th>Insta</th>
                                        <th>Fb</th>
                                        <th>Twitter</th>
                                        <th>Linkedin</th>
                                        <th>Setting</th>
                                    </tr>
                                </thead>
                                <tbody>

                                    @foreach (var Model in Model)
                                    {
                                        <tr>
                                            <td>@Model.Location</td>
                                            <td>@Model.Phone</td>
                                            <td>@Model.Mail</td>
                                            <td>@Model.Insta</td>
                                            <td>@Model.Facebook</td>
                                            <td>@Model.Twitter</td>
                                            <td>@Model.Linkedin</td>
                                            <td>
                                                <a class="btn btn-danger" asp-controller="Bio" asp-action="Delete" asp-route-id="@Model.Id">Delete</a>
                                                <a class="btn btn-dark" asp-controller="Bio" asp-action="Update" asp-route-id="@Model.Id">Update</a>
                                                <a class="btn btn-success" asp-controller="Bio" asp-action="Detail" asp-route-id="@Model.Id">Detail</a>

                                            </td>
                                        </tr>
                                    }

                                </tbody>
                            </table>

                        </div>
                </div>
            </div>
        </div>
    </div>
}
else
{
    <a asp-controller="slider" asp-action="Create" class="btn btn-primary">Create</a>
    <h1>Bosdu</h1>
}

Pet_Shop-Backend/Pet_Shop/Areas/AdminF/Views/Bio/Update.cshtml
@model Bio
@{
    ViewData["Title"] = "Create";
    Layout = "~/Areas/AdminF/Views/Shared/_AdminLayout.cshtml";
}
<div class="container">
    <div class="row">
        <div class="col=md-12">
            <form class="forms-sample" method="post" enctype="multipart/form-data">

                <div class="form-group">
                    <label asp-for="Location">Location</label>
                    <input asp-for="Location" class="form-control" placeholder="Location">
                    <span asp-validation-for="Location"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Mail">Mail</label>
                    <input asp-for="Mail" class="form-control" placeholder="Mail">
                    <span asp-validation-for="Mail"></span>

                </div>
                <div class="form-group">
                    <label asp-for="Insta">Insta</label>
                    <input asp-for="Insta" class="form-control" placeholder="Insta">
                    <span asp-validation-for="Insta"></span>

                </div>
                <div class="form-group">
                    <label asp-for="Linkedin">Linkedin</label>
                    <input asp-for="Linkedin" class="form-control" placeholder="Linkedin">
                    <span asp-validation-for="Linkedin"></span>

                </div>
                <div class="form-group">
                    <label asp-for="Twitter">Twitter</label>
                    <input asp-for="Twitter" class="form-control" placeholder="Twitter">
                    <span asp-validation-for="Twitter"></span>

                </div>
                <div class="form-group">
                    <label asp-for="Facebook">Facebook</label>
                    <input asp-for="Facebook" class="form-control" placeholder="Facebook">
                    <span asp-validation-for="Facebook"></span>

                </div>
                <div class="form-group">
                    <label asp-for="Phone">Phone</label>
                    <input asp-for="Phone" class="form-control" placeholder="Phone">
                    <span asp-validation-for="Phone"></span>

                </div>
                <button type="submit" class="btn btn-primary mr-2">Create</button>
                <a asp-controller="bio" asp-action="Index" class="btn btn-primary">Back</a>
            </form>
        </div>

    </div>
</div>